spring.application.name=CryptoInfosys
# Database config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:crypto_portfolio;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port (Render requirement)
server.port=${PORT:8080}


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# JWT
jwt.secret=${JWT_SECRET:change-me-to-a-very-long-secret-key-for-prod-1234567890}
jwt.expirationMs=${JWT_EXPIRATION_MS:900000}
jwt.refreshExpirationMs=${JWT_REFRESH_EXPIRATION_MS:604800000}

# Mail server configuration
spring.mail.host=${SMTP_HOST:localhost}
spring.mail.port=${SMTP_PORT:1025}
spring.mail.username=${GMAIL_USERNAME:}
spring.mail.password=${GMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:false}


# Gemini API Key
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com}

app.crypto.secret=${APP_CRYPTO_SECRET:0123456789abcdef0123456789abcdef}


